export { default as Socket } from './src/Socket'
export type { SocketOptions } from './src/types'
export { parseSocketError, isValidationError } from './src/errors'
export { default as ProgressPromise } from './src/ProgressPromise'
export * as types from './src/types'
